services:
    chat:
        image: chat:0.1.0-dev
        container_name: chat-dev
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "6001:8080"
        environment:
            - DEBUG=false
            - TZ=Asia/Shanghai
            - DOCKER_CONTAINER=true
        depends_on:
            - mongo
        volumes:
            - ./volumes/logs:/usr/src/app/logs
            - ./:/usr/src/app/
        restart: always
        networks:
            - chat-network
    mongo:
        image: mongo:latest
        container_name: chat-db-dev
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password1234
        # ports:
        #     - 27017:27017
        volumes:
            - ./volumes/mongodb_data:/data/db
        networks:
            - chat-network
    mongo-express:
        image: mongo-express
        container_name: chat-db-express-dev
        restart: always
        ports:
            - 8085:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password1234
            ME_CONFIG_MONGODB_URL: mongodb://root:password1234@mongo:27017/
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin1234
        depends_on:
            - mongo
        networks:
            - chat-network
networks:
    chat-network:
        name: chat-network
